# Generated by Django 5.2.4 on 2025-07-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_profile_image_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/assets/default_user_profile.jpg', upload_to='profile_images/'),
        ),
    ]
